### ISSUE TITLE
Unsure where the markdown file is created

### ISSUE THREAD

**Issue by ngirard** [basementuniverse/vscode-kanbn#1]
Heya,

after stumbling on your extension, I had hopes that I would be able to integrate it with [Markdown Memo](https://github.com/svsool/vscode-memo), i.e. that I would have a `todo.md` in my workspace that could be
1. open & edited using both Markdown Memo and Kanbn ;
2. shared between coworkers (our workspace is versioned using Git and shared between us)

Unfortunately, after "initiating" the board, I couldn't find the associated markdown file and have no clue where it could be.

Thanks anyway for involving your time & energy into this seemingly nice extension !

**Comment by gordon-winkel** [comment]
Hi @ngirard,

During initialisation Kanbn should create a directory called `.kanbn` inside your workspace directory. This directory should contain the index file (`.kanbn/index.md`; this contains all of the columns and a list of tasks for each column).

There will also be a `.kanbn/tasks` directory, which will contain all of your tasks as separate `<task_id>.md` files.

Let me know if this directory doesn't exist after initialising Kanbn, or if there's anything else I can help with :smiley:

I've created a bit of documentation about index & task structure which you might find helpful:
* https://github.com/basementuniverse/kanbn/blob/master/docs/index-structure.md
* https://github.com/basementuniverse/kanbn/blob/master/docs/task-structure.md

Integrating with Markdown Memo sounds like a great idea! I really like the concept of having documentation and task management living in the project repository, alongside the code, where it can be shared and versioned.

Thanks :smile:

**Comment by ngirard** [comment]
@gordon-winkel,

thanks for your feedback and your responsiveness !

Your docs were indeed informative, and enough to close this issue.

I ripgrepped wherever I could think of, but didn't expect the file(s) to be burried into a hidden directory ! I wish to elaborate further on that, but I'll open a new issue. Same for the Markdown Memo integration.

Cheers
