### ISSUE TITLE
YAML metadata: switch to the standard front matter

### ISSUE THREAD

**Issue by ngirard** [basementuniverse/vscode-kanbn#3]
I feel like this title alone betrays me as a non-english native, but whatever ;-)

As per https://github.com/basementuniverse/kanbn/blob/master/docs/task-structure.md and from my tests files, it appears that the way you're serializing the YAML metadata is highly non-standard.

As far as I know, the standard(*) adopted by most markdown-related software consist in a so-called "YAML front-matter", positioned at the very top of a Markdown document, and enclosed between 3 dashes:
```md
---
title: This is an example of YAML front matter in a sample document
key: value
---

The rest of the document
```

Adopting this standard would allow your code and tools to be able to interoperate with others ; on the contrary, keeping your own convention prevents you and your users from having their documents handled by other tools.

Your project seems much more thought out that the other Kanban extensions for VS Code, and you seem to be dedicated to it, so it wouldn't take much more efforts to create an [Obsidian](obsidian.md) plugin out of it, which would be appreciated by many people. Would you be willing to do so, switching to the abovementionned standard would be required.

(*) *de facto* standard, since it was decided [not to add it](https://talk.commonmark.org/t/front-matter-best-practice/2235/3) to the CommonMark specification.

**Comment by basementuniverse** [comment]
I agree that this would be better. I read about YFM during development of Kanbn, but for some reason I still decided to put index & task metadata inside a code block underneath a markdown heading...

As you mentioned, this will allow Kanbn to integrate more easily with other tools. Plus, sticking to established and community-accepted standards is always a good thing :smile:

I'll try to make this change tonight. It should be fairly simple, all of the [index](https://github.com/basementuniverse/kanbn/blob/master/src/parse-index.js) & [task](https://github.com/basementuniverse/kanbn/blob/master/src/parse-task.js) serialization/deserialization code exists in one place.

Thanks!

**Comment by ngirard** [comment]
Well thank you for your commitment !

**Comment by basementuniverse** [comment]
Kanbn [has been updated](https://github.com/basementuniverse/kanbn/releases/tag/0.5.0) to use YAML front matter for index options and task metadata. The `## Options` and `## Metadata` headings are still supported when parsing markdown files for backwards compatibility, but now when we save a file any options/metadata will be saved as YMF.

Additionally, the VSCode extension has been updated to use Kanbn 0.5.0.

_Note: your index files and tasks should still work correctly, and will automatically convert from embedded YAML to YMF when you use a Kanbn command or this VSCode extension to modify them. However, if you would like to convert everything to the new format right away, use the following Kanbn CLI command (will require [Kanbn](https://github.com/basementuniverse/kanbn) to be installed):_

`kanbn validate --save`

Thanks for the feedback and suggestions!
