### ISSUE TITLE
The window stops working sometimes

### ISSUE THREAD

**Issue by fanshibear** [basementuniverse/vscode-kanbn#7]
Hello,

The window stops working sometimes after dragging or saving a few cards and items become unclickable. It usually recovers in about ten seconds.

**Comment by basementuniverse** [comment]
Hi @fanshibear, thanks for reporting this - it has happened a few times on my machine too. I suspect there are memory leaks in the board component (or I'm missing a `useState` / `useCallback` hook somewhere).

I'll do some profiling / optimisation, and will hopefully have an update ready soon.

**Comment by basementuniverse** [comment]
I have released `0.9.3` which should hopefully sort out the performance bug.

As I suspected, I wasn't adding the Webview message event handler inside a `useEffect` hook, so every time the board got updated it was adding a new event handler on top of the old one. This was causing the UI to freeze pretty quickly!

I have done some manual performance testing and it seems to be working quite well now. Please let me know if the bug still occurs after you've updated the extension :smile:

Thanks!

**Comment by fanshibear** [comment]
It works well on my computer now. I like it better 😄 

Thanks!
